/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Aug 20 13:35:55 2018. */

#include "fsm_cckconfig_clientinfo.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fsm_ClientInfo_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, fsm_ClientInfo, id, id, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, fsm_ClientInfo, ip, id, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, fsm_ClientInfo, subnetmask, ip, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, fsm_ClientInfo, gateway, subnetmask, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, fsm_ClientInfo, iid, gateway, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
