/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Aug 20 13:35:55 2018. */

#include "fsm_cckconfig_MN.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fsm_MN921_MB_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_MN921_MB, TimeOutputCall, TimeOutputCall, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN921_CB_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_MN921_CB, TimeOutputCall, TimeOutputCall, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN921_TCH_fields[6] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fsm_MN921_TCH, typetch, typetch, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN921_TCH, TimeOutputCall, typetch, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN921_TCH, MinTimeOutputCall, TimeOutputCall, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN921_TCH, MaxTimeOutputCall, MinTimeOutputCall, 0),
    PB_FIELD(  5, UENUM   , SINGULAR, STATIC  , OTHER, fsm_MN921_TCH, ocfr, MaxTimeOutputCall, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN921_ATS_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, fsm_MN921_ATS, typeats, typeats, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN825_R168C_fields[2] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_MN825_R168C, TimeOutputCall, TimeOutputCall, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN_Channel_fields[12] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_MN_Channel, self_sip_port, self_sip_port, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, self_rtp_port, self_sip_port, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, self_sip_number, self_rtp_port, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, volume, self_sip_number, 0),
    PB_FIELD(  5, UENUM   , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, typedev, volume, 0),
    PB_FIELD(  6, UINT32  , REPEATED, STATIC  , OTHER, fsm_MN_Channel, SubscriberForCall, typedev, 0),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, mb, SubscriberForCall, &fsm_MN921_MB_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, cb, mb, &fsm_MN921_CB_fields),
    PB_FIELD(  9, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, tch, cb, &fsm_MN921_TCH_fields),
    PB_FIELD( 10, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, ats, tch, &fsm_MN921_ATS_fields),
    PB_FIELD( 11, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_MN_Channel, r168, ats, &fsm_MN825_R168C_fields),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN825_R168_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_MN825_R168, r168port, r168port, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fsm_MN825_R168, apd, r168port, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_MN_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, fsm_MN, client, client, &fsm_ClientInfo_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_MN, r168, client, &fsm_MN825_R168_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, fsm_MN, channel, r168, &fsm_MN_Channel_fields),
    PB_LAST_FIELD
};






/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fsm_MN_Channel, mb) < 65536 && pb_membersize(fsm_MN_Channel, cb) < 65536 && pb_membersize(fsm_MN_Channel, tch) < 65536 && pb_membersize(fsm_MN_Channel, ats) < 65536 && pb_membersize(fsm_MN_Channel, r168) < 65536 && pb_membersize(fsm_MN, client) < 65536 && pb_membersize(fsm_MN, r168) < 65536 && pb_membersize(fsm_MN, channel[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_fsm_MN921_MB_fsm_MN921_CB_fsm_MN921_TCH_fsm_MN921_ATS_fsm_MN825_R168C_fsm_MN_Channel_fsm_MN825_R168_fsm_MN)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fsm_MN_Channel, mb) < 256 && pb_membersize(fsm_MN_Channel, cb) < 256 && pb_membersize(fsm_MN_Channel, tch) < 256 && pb_membersize(fsm_MN_Channel, ats) < 256 && pb_membersize(fsm_MN_Channel, r168) < 256 && pb_membersize(fsm_MN, client) < 256 && pb_membersize(fsm_MN, r168) < 256 && pb_membersize(fsm_MN, channel[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_fsm_MN921_MB_fsm_MN921_CB_fsm_MN921_TCH_fsm_MN921_ATS_fsm_MN825_R168C_fsm_MN_Channel_fsm_MN825_R168_fsm_MN)
#endif


/* @@protoc_insertion_point(eof) */
