/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Aug 20 13:35:56 2018. */

#include "fsm_cckconfig_PO.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t fsm_P0_Group_subel_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, fsm_P0_Group_subel, abonent, abonent, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_P0_Group_el_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, fsm_P0_Group_el, grp, grp, &fsm_P0_Group_subel_fields),
    PB_LAST_FIELD
};

const pb_field_t fsm_P0_Group_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, fsm_P0_Group, cnfg, cnfg, &fsm_P0_Group_el_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_P0_Group, csvg, cnfg, &fsm_P0_Group_el_fields),
    PB_LAST_FIELD
};

const pb_field_t fsm_PO_Subscriber_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_PO_Subscriber, sip_number, sip_number, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fsm_PO_Subscriber, flags, sip_number, 0),
    PB_LAST_FIELD
};

const pb_field_t fsm_PO_Channel_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, fsm_PO_Channel, self_sip_port, self_sip_port, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, fsm_PO_Channel, self_rtp_port, self_sip_port, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, fsm_PO_Channel, self_sip_number, self_rtp_port, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, fsm_PO_Channel, volume, self_sip_number, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, fsm_PO_Channel, SubscriberForCall, volume, &fsm_PO_Subscriber_fields),
    PB_LAST_FIELD
};

const pb_field_t fsm_P0_fields[5] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, fsm_P0, client, client, &fsm_ClientInfo_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, fsm_P0, grp, client, &fsm_P0_Group_fields),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, fsm_P0, mac, grp, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, fsm_P0, channel, mac, &fsm_PO_Channel_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fsm_P0_Group_el, grp[0]) < 65536 && pb_membersize(fsm_P0_Group, cnfg) < 65536 && pb_membersize(fsm_P0_Group, csvg) < 65536 && pb_membersize(fsm_PO_Channel, SubscriberForCall[0]) < 65536 && pb_membersize(fsm_P0, client) < 65536 && pb_membersize(fsm_P0, grp) < 65536 && pb_membersize(fsm_P0, channel[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_fsm_P0_Group_subel_fsm_P0_Group_el_fsm_P0_Group_fsm_PO_Subscriber_fsm_PO_Channel_fsm_P0)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(fsm_P0_Group_el, grp[0]) < 256 && pb_membersize(fsm_P0_Group, cnfg) < 256 && pb_membersize(fsm_P0_Group, csvg) < 256 && pb_membersize(fsm_PO_Channel, SubscriberForCall[0]) < 256 && pb_membersize(fsm_P0, client) < 256 && pb_membersize(fsm_P0, grp) < 256 && pb_membersize(fsm_P0, channel[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_fsm_P0_Group_subel_fsm_P0_Group_el_fsm_P0_Group_fsm_PO_Subscriber_fsm_PO_Channel_fsm_P0)
#endif


/* @@protoc_insertion_point(eof) */
