/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Mon Aug 20 13:35:55 2018. */

#ifndef PB_FSM_FSM_CCKCONFIG_CLIENTINFO_PB_H_INCLUDED
#define PB_FSM_FSM_CCKCONFIG_CLIENTINFO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _fsm_ClientInfo {
    int32_t id;
    int32_t ip;
    int32_t subnetmask;
    int32_t gateway;
    int32_t iid;
/* @@protoc_insertion_point(struct:fsm_ClientInfo) */
} fsm_ClientInfo;

/* Default values for struct fields */

/* Initializer values for message structs */
#define fsm_ClientInfo_init_default              {0, 0, 0, 0, 0}
#define fsm_ClientInfo_init_zero                 {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define fsm_ClientInfo_id_tag                    1
#define fsm_ClientInfo_ip_tag                    2
#define fsm_ClientInfo_subnetmask_tag            3
#define fsm_ClientInfo_gateway_tag               4
#define fsm_ClientInfo_iid_tag                   5

/* Struct field encoding specification for nanopb */
extern const pb_field_t fsm_ClientInfo_fields[6];

/* Maximum encoded size of messages (where known) */
#define fsm_ClientInfo_size                      55

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FSM_CCKCONFIG_CLIENTINFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
