// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fsm_cckconfig_clientinfo.proto

#ifndef PROTOBUF_INCLUDED_fsm_5fcckconfig_5fclientinfo_2eproto
#define PROTOBUF_INCLUDED_fsm_5fcckconfig_5fclientinfo_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fclientinfo_2eproto 

namespace protobuf_fsm_5fcckconfig_5fclientinfo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_fsm_5fcckconfig_5fclientinfo_2eproto
namespace fsm {
class ClientInfo;
class ClientInfoDefaultTypeInternal;
extern ClientInfoDefaultTypeInternal _ClientInfo_default_instance_;
}  // namespace fsm
namespace google {
namespace protobuf {
template<> ::fsm::ClientInfo* Arena::CreateMaybeMessage<::fsm::ClientInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace fsm {

// ===================================================================

class ClientInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fsm.ClientInfo) */ {
 public:
  ClientInfo();
  virtual ~ClientInfo();

  ClientInfo(const ClientInfo& from);

  inline ClientInfo& operator=(const ClientInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ClientInfo(ClientInfo&& from) noexcept
    : ClientInfo() {
    *this = ::std::move(from);
  }

  inline ClientInfo& operator=(ClientInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientInfo* internal_default_instance() {
    return reinterpret_cast<const ClientInfo*>(
               &_ClientInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ClientInfo* other);
  friend void swap(ClientInfo& a, ClientInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ClientInfo* New() const final {
    return CreateMaybeMessage<ClientInfo>(NULL);
  }

  ClientInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ClientInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ClientInfo& from);
  void MergeFrom(const ClientInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 ip = 2;
  void clear_ip();
  static const int kIpFieldNumber = 2;
  ::google::protobuf::int32 ip() const;
  void set_ip(::google::protobuf::int32 value);

  // int32 subnetmask = 3;
  void clear_subnetmask();
  static const int kSubnetmaskFieldNumber = 3;
  ::google::protobuf::int32 subnetmask() const;
  void set_subnetmask(::google::protobuf::int32 value);

  // int32 gateway = 4;
  void clear_gateway();
  static const int kGatewayFieldNumber = 4;
  ::google::protobuf::int32 gateway() const;
  void set_gateway(::google::protobuf::int32 value);

  // int32 iid = 5;
  void clear_iid();
  static const int kIidFieldNumber = 5;
  ::google::protobuf::int32 iid() const;
  void set_iid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fsm.ClientInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 ip_;
  ::google::protobuf::int32 subnetmask_;
  ::google::protobuf::int32 gateway_;
  ::google::protobuf::int32 iid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fsm_5fcckconfig_5fclientinfo_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientInfo

// int32 id = 1;
inline void ClientInfo::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 ClientInfo::id() const {
  // @@protoc_insertion_point(field_get:fsm.ClientInfo.id)
  return id_;
}
inline void ClientInfo::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:fsm.ClientInfo.id)
}

// int32 ip = 2;
inline void ClientInfo::clear_ip() {
  ip_ = 0;
}
inline ::google::protobuf::int32 ClientInfo::ip() const {
  // @@protoc_insertion_point(field_get:fsm.ClientInfo.ip)
  return ip_;
}
inline void ClientInfo::set_ip(::google::protobuf::int32 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:fsm.ClientInfo.ip)
}

// int32 subnetmask = 3;
inline void ClientInfo::clear_subnetmask() {
  subnetmask_ = 0;
}
inline ::google::protobuf::int32 ClientInfo::subnetmask() const {
  // @@protoc_insertion_point(field_get:fsm.ClientInfo.subnetmask)
  return subnetmask_;
}
inline void ClientInfo::set_subnetmask(::google::protobuf::int32 value) {
  
  subnetmask_ = value;
  // @@protoc_insertion_point(field_set:fsm.ClientInfo.subnetmask)
}

// int32 gateway = 4;
inline void ClientInfo::clear_gateway() {
  gateway_ = 0;
}
inline ::google::protobuf::int32 ClientInfo::gateway() const {
  // @@protoc_insertion_point(field_get:fsm.ClientInfo.gateway)
  return gateway_;
}
inline void ClientInfo::set_gateway(::google::protobuf::int32 value) {
  
  gateway_ = value;
  // @@protoc_insertion_point(field_set:fsm.ClientInfo.gateway)
}

// int32 iid = 5;
inline void ClientInfo::clear_iid() {
  iid_ = 0;
}
inline ::google::protobuf::int32 ClientInfo::iid() const {
  // @@protoc_insertion_point(field_get:fsm.ClientInfo.iid)
  return iid_;
}
inline void ClientInfo::set_iid(::google::protobuf::int32 value) {
  
  iid_ = value;
  // @@protoc_insertion_point(field_set:fsm.ClientInfo.iid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace fsm

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_fsm_5fcckconfig_5fclientinfo_2eproto
