// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fsm_cckconfig_service.proto

#ifndef PROTOBUF_INCLUDED_fsm_5fcckconfig_5fservice_2eproto
#define PROTOBUF_INCLUDED_fsm_5fcckconfig_5fservice_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "fsm_cckconfig_MN.pb.h"
#include "fsm_cckconfig_MN401.pb.h"
#include "fsm_cckconfig_PO.pb.h"
#include "fsm_cckconfig_VirtPO.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fservice_2eproto 

namespace protobuf_fsm_5fcckconfig_5fservice_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_fsm_5fcckconfig_5fservice_2eproto
namespace fsm {
class GetDeviceRq;
class GetDeviceRqDefaultTypeInternal;
extern GetDeviceRqDefaultTypeInternal _GetDeviceRq_default_instance_;
class SetDeviceResp;
class SetDeviceRespDefaultTypeInternal;
extern SetDeviceRespDefaultTypeInternal _SetDeviceResp_default_instance_;
}  // namespace fsm
namespace google {
namespace protobuf {
template<> ::fsm::GetDeviceRq* Arena::CreateMaybeMessage<::fsm::GetDeviceRq>(Arena*);
template<> ::fsm::SetDeviceResp* Arena::CreateMaybeMessage<::fsm::SetDeviceResp>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace fsm {

// ===================================================================

class GetDeviceRq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fsm.GetDeviceRq) */ {
 public:
  GetDeviceRq();
  virtual ~GetDeviceRq();

  GetDeviceRq(const GetDeviceRq& from);

  inline GetDeviceRq& operator=(const GetDeviceRq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetDeviceRq(GetDeviceRq&& from) noexcept
    : GetDeviceRq() {
    *this = ::std::move(from);
  }

  inline GetDeviceRq& operator=(GetDeviceRq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetDeviceRq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetDeviceRq* internal_default_instance() {
    return reinterpret_cast<const GetDeviceRq*>(
               &_GetDeviceRq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GetDeviceRq* other);
  friend void swap(GetDeviceRq& a, GetDeviceRq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetDeviceRq* New() const final {
    return CreateMaybeMessage<GetDeviceRq>(NULL);
  }

  GetDeviceRq* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GetDeviceRq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GetDeviceRq& from);
  void MergeFrom(const GetDeviceRq& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDeviceRq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fsm.GetDeviceRq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fsm_5fcckconfig_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SetDeviceResp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fsm.SetDeviceResp) */ {
 public:
  SetDeviceResp();
  virtual ~SetDeviceResp();

  SetDeviceResp(const SetDeviceResp& from);

  inline SetDeviceResp& operator=(const SetDeviceResp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetDeviceResp(SetDeviceResp&& from) noexcept
    : SetDeviceResp() {
    *this = ::std::move(from);
  }

  inline SetDeviceResp& operator=(SetDeviceResp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SetDeviceResp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetDeviceResp* internal_default_instance() {
    return reinterpret_cast<const SetDeviceResp*>(
               &_SetDeviceResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SetDeviceResp* other);
  friend void swap(SetDeviceResp& a, SetDeviceResp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetDeviceResp* New() const final {
    return CreateMaybeMessage<SetDeviceResp>(NULL);
  }

  SetDeviceResp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SetDeviceResp>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SetDeviceResp& from);
  void MergeFrom(const SetDeviceResp& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetDeviceResp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:fsm.SetDeviceResp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 status_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_fsm_5fcckconfig_5fservice_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetDeviceRq

// int32 id = 1;
inline void GetDeviceRq::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 GetDeviceRq::id() const {
  // @@protoc_insertion_point(field_get:fsm.GetDeviceRq.id)
  return id_;
}
inline void GetDeviceRq::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:fsm.GetDeviceRq.id)
}

// -------------------------------------------------------------------

// SetDeviceResp

// int32 status = 1;
inline void SetDeviceResp::clear_status() {
  status_ = 0;
}
inline ::google::protobuf::int32 SetDeviceResp::status() const {
  // @@protoc_insertion_point(field_get:fsm.SetDeviceResp.status)
  return status_;
}
inline void SetDeviceResp::set_status(::google::protobuf::int32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:fsm.SetDeviceResp.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fsm

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_fsm_5fcckconfig_5fservice_2eproto
