/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Tue Jun 19 19:11:20 2018. */

#ifndef PB_JSON2PROTO_MN921_CB_PB_H_INCLUDED
#define PB_JSON2PROTO_MN921_CB_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _json2proto_json2proto_MN921_CB_CB {
    int32_t ToneOutputCallPulse;
/* @@protoc_insertion_point(struct:json2proto_json2proto_MN921_CB_CB) */
} json2proto_json2proto_MN921_CB_CB;

typedef struct _json2proto_json2proto_MN921_CB_SubscriberForCall {
    char abonent[5];
    int32_t id;
/* @@protoc_insertion_point(struct:json2proto_json2proto_MN921_CB_SubscriberForCall) */
} json2proto_json2proto_MN921_CB_SubscriberForCall;

typedef struct _json2proto_json2proto_MN921_CB {
    char self_sip_description[5];
    int32_t type_channel;
    int32_t self_port;
    json2proto_json2proto_MN921_CB_CB CB;
    pb_size_t SubscriberForCall_count;
    json2proto_json2proto_MN921_CB_SubscriberForCall SubscriberForCall[4];
    int32_t channel;
    int32_t audio_port;
/* @@protoc_insertion_point(struct:json2proto_json2proto_MN921_CB) */
} json2proto_json2proto_MN921_CB;

/* Default values for struct fields */

/* Initializer values for message structs */
#define json2proto_json2proto_MN921_CB_init_default {"", 0, 0, json2proto_json2proto_MN921_CB_CB_init_default, 0, {json2proto_json2proto_MN921_CB_SubscriberForCall_init_default, json2proto_json2proto_MN921_CB_SubscriberForCall_init_default, json2proto_json2proto_MN921_CB_SubscriberForCall_init_default, json2proto_json2proto_MN921_CB_SubscriberForCall_init_default}, 0, 0}
#define json2proto_json2proto_MN921_CB_CB_init_default {0}
#define json2proto_json2proto_MN921_CB_SubscriberForCall_init_default {"", 0}
#define json2proto_json2proto_MN921_CB_init_zero {"", 0, 0, json2proto_json2proto_MN921_CB_CB_init_zero, 0, {json2proto_json2proto_MN921_CB_SubscriberForCall_init_zero, json2proto_json2proto_MN921_CB_SubscriberForCall_init_zero, json2proto_json2proto_MN921_CB_SubscriberForCall_init_zero, json2proto_json2proto_MN921_CB_SubscriberForCall_init_zero}, 0, 0}
#define json2proto_json2proto_MN921_CB_CB_init_zero {0}
#define json2proto_json2proto_MN921_CB_SubscriberForCall_init_zero {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define json2proto_json2proto_MN921_CB_CB_ToneOutputCallPulse_tag 1
#define json2proto_json2proto_MN921_CB_SubscriberForCall_abonent_tag 1
#define json2proto_json2proto_MN921_CB_SubscriberForCall_id_tag 2
#define json2proto_json2proto_MN921_CB_self_sip_description_tag 1
#define json2proto_json2proto_MN921_CB_type_channel_tag 2
#define json2proto_json2proto_MN921_CB_self_port_tag 3
#define json2proto_json2proto_MN921_CB_CB_tag    4
#define json2proto_json2proto_MN921_CB_SubscriberForCall_tag 5
#define json2proto_json2proto_MN921_CB_channel_tag 6
#define json2proto_json2proto_MN921_CB_audio_port_tag 7

/* Struct field encoding specification for nanopb */
extern const pb_field_t json2proto_json2proto_MN921_CB_fields[8];
extern const pb_field_t json2proto_json2proto_MN921_CB_CB_fields[2];
extern const pb_field_t json2proto_json2proto_MN921_CB_SubscriberForCall_fields[3];

/* Maximum encoded size of messages (where known) */
#define json2proto_json2proto_MN921_CB_size      144
#define json2proto_json2proto_MN921_CB_CB_size   11
#define json2proto_json2proto_MN921_CB_SubscriberForCall_size 18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MN921_CB_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
