/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Jun 19 19:11:19 2018. */

#include "MN921_ATS.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t json2proto_json2proto_MN921_ATS_fields[8] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_ATS, ATS, ATS, &json2proto_json2proto_MN921_ATS_ATS_fields),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS, self_sip_description, ATS, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS, type_channel, self_sip_description, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS, self_port, type_channel, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, json2proto_json2proto_MN921_ATS, SubscriberForCall, self_port, &json2proto_json2proto_MN921_ATS_SubscriberForCall_fields),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS, audio_port, SubscriberForCall, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS, channel, audio_port, 0),
    PB_LAST_FIELD
};

const pb_field_t json2proto_json2proto_MN921_ATS_ATS_fields[7] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_ATS_ATS, Type, Type, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS_ATS, AtsR2Priority, Type, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS_ATS, AtsR2SNRDtmf, AtsR2Priority, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, json2proto_json2proto_MN921_ATS_ATS, SelfNumber, AtsR2SNRDtmf, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, json2proto_json2proto_MN921_ATS_ATS, TargetNumber, SelfNumber, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS_ATS, AtsR2SNRLin, TargetNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t json2proto_json2proto_MN921_ATS_SubscriberForCall_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_ATS_SubscriberForCall, abonent, abonent, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_ATS_SubscriberForCall, id, abonent, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(json2proto_json2proto_MN921_ATS, ATS) < 65536 && pb_membersize(json2proto_json2proto_MN921_ATS, SubscriberForCall[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_json2proto_json2proto_MN921_ATS_json2proto_json2proto_MN921_ATS_ATS_json2proto_json2proto_MN921_ATS_SubscriberForCall)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(json2proto_json2proto_MN921_ATS, ATS) < 256 && pb_membersize(json2proto_json2proto_MN921_ATS, SubscriberForCall[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_json2proto_json2proto_MN921_ATS_json2proto_json2proto_MN921_ATS_ATS_json2proto_json2proto_MN921_ATS_SubscriberForCall)
#endif


/* @@protoc_insertion_point(eof) */
