/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Jun 19 19:11:20 2018. */

#include "MN921_CB.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t json2proto_json2proto_MN921_CB_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_CB, self_sip_description, self_sip_description, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_CB, type_channel, self_sip_description, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_CB, self_port, type_channel, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_CB, CB, self_port, &json2proto_json2proto_MN921_CB_CB_fields),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, json2proto_json2proto_MN921_CB, SubscriberForCall, CB, &json2proto_json2proto_MN921_CB_SubscriberForCall_fields),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_CB, channel, SubscriberForCall, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_CB, audio_port, channel, 0),
    PB_LAST_FIELD
};

const pb_field_t json2proto_json2proto_MN921_CB_CB_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_CB_CB, ToneOutputCallPulse, ToneOutputCallPulse, 0),
    PB_LAST_FIELD
};

const pb_field_t json2proto_json2proto_MN921_CB_SubscriberForCall_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_CB_SubscriberForCall, abonent, abonent, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_CB_SubscriberForCall, id, abonent, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(json2proto_json2proto_MN921_CB, CB) < 65536 && pb_membersize(json2proto_json2proto_MN921_CB, SubscriberForCall[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_json2proto_json2proto_MN921_CB_json2proto_json2proto_MN921_CB_CB_json2proto_json2proto_MN921_CB_SubscriberForCall)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(json2proto_json2proto_MN921_CB, CB) < 256 && pb_membersize(json2proto_json2proto_MN921_CB, SubscriberForCall[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_json2proto_json2proto_MN921_CB_json2proto_json2proto_MN921_CB_CB_json2proto_json2proto_MN921_CB_SubscriberForCall)
#endif


/* @@protoc_insertion_point(eof) */
