/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon May 21 13:33:25 2018. */

#include "MN921_server.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t json2proto_json2proto_MN921_server_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, json2proto_json2proto_MN921_server, server_sip_port, server_sip_port, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_server, gateway, server_sip_port, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_server, server_ip, gateway, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_server, self_ip, server_ip, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, json2proto_json2proto_MN921_server, subnet_mask, self_ip, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
