// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fsm_cckconfig_PO.proto

#include "fsm_cckconfig_PO.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_fsm_5fcckconfig_5fPO_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fPO_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_P0_Group_subel;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fPO_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PO_Subscriber;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fPO_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_P0_Group;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fPO_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_P0_Group_el;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fPO_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_PO_Channel;
}  // namespace protobuf_fsm_5fcckconfig_5fPO_2eproto
namespace protobuf_fsm_5fcckconfig_5fclientinfo_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fsm_5fcckconfig_5fclientinfo_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ClientInfo;
}  // namespace protobuf_fsm_5fcckconfig_5fclientinfo_2eproto
namespace fsm {
class P0_Group_subelDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<P0_Group_subel>
      _instance;
} _P0_Group_subel_default_instance_;
class P0_Group_elDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<P0_Group_el>
      _instance;
} _P0_Group_el_default_instance_;
class P0_GroupDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<P0_Group>
      _instance;
} _P0_Group_default_instance_;
class PO_SubscriberDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PO_Subscriber>
      _instance;
} _PO_Subscriber_default_instance_;
class PO_ChannelDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PO_Channel>
      _instance;
} _PO_Channel_default_instance_;
class P0DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<P0>
      _instance;
} _P0_default_instance_;
}  // namespace fsm
namespace protobuf_fsm_5fcckconfig_5fPO_2eproto {
static void InitDefaultsP0_Group_subel() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fsm::_P0_Group_subel_default_instance_;
    new (ptr) ::fsm::P0_Group_subel();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fsm::P0_Group_subel::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_P0_Group_subel =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsP0_Group_subel}, {}};

static void InitDefaultsP0_Group_el() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fsm::_P0_Group_el_default_instance_;
    new (ptr) ::fsm::P0_Group_el();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fsm::P0_Group_el::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_P0_Group_el =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsP0_Group_el}, {
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group_subel.base,}};

static void InitDefaultsP0_Group() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fsm::_P0_Group_default_instance_;
    new (ptr) ::fsm::P0_Group();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fsm::P0_Group::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_P0_Group =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsP0_Group}, {
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group_el.base,}};

static void InitDefaultsPO_Subscriber() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fsm::_PO_Subscriber_default_instance_;
    new (ptr) ::fsm::PO_Subscriber();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fsm::PO_Subscriber::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PO_Subscriber =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPO_Subscriber}, {}};

static void InitDefaultsPO_Channel() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fsm::_PO_Channel_default_instance_;
    new (ptr) ::fsm::PO_Channel();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fsm::PO_Channel::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_PO_Channel =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPO_Channel}, {
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_PO_Subscriber.base,}};

static void InitDefaultsP0() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::fsm::_P0_default_instance_;
    new (ptr) ::fsm::P0();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::fsm::P0::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_P0 =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsP0}, {
      &protobuf_fsm_5fcckconfig_5fclientinfo_2eproto::scc_info_ClientInfo.base,
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group.base,
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_PO_Channel.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_P0_Group_subel.base);
  ::google::protobuf::internal::InitSCC(&scc_info_P0_Group_el.base);
  ::google::protobuf::internal::InitSCC(&scc_info_P0_Group.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PO_Subscriber.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PO_Channel.base);
  ::google::protobuf::internal::InitSCC(&scc_info_P0.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group_subel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group_subel, abonent_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group_el, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group_el, grp_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group, cnfg_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0_Group, csvg_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Subscriber, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Subscriber, sip_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Subscriber, flags_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Channel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Channel, self_sip_port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Channel, self_rtp_port_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Channel, self_sip_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Channel, volume_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::PO_Channel, subscriberforcall_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0, client_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0, grp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0, mac_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::fsm::P0, channel_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::fsm::P0_Group_subel)},
  { 6, -1, sizeof(::fsm::P0_Group_el)},
  { 12, -1, sizeof(::fsm::P0_Group)},
  { 19, -1, sizeof(::fsm::PO_Subscriber)},
  { 26, -1, sizeof(::fsm::PO_Channel)},
  { 36, -1, sizeof(::fsm::P0)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::fsm::_P0_Group_subel_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::fsm::_P0_Group_el_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::fsm::_P0_Group_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::fsm::_PO_Subscriber_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::fsm::_PO_Channel_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::fsm::_P0_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "fsm_cckconfig_PO.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026fsm_cckconfig_PO.proto\022\003fsm\032\014nanopb.pr"
      "oto\032\036fsm_cckconfig_clientinfo.proto\"(\n\016P"
      "0_Group_subel\022\026\n\007abonent\030\001 \003(\rB\005\222\?\002\020\n\"6\n"
      "\013P0_Group_el\022\'\n\003grp\030\001 \003(\0132\023.fsm.P0_Group"
      "_subelB\005\222\?\002\020\004\"J\n\010P0_Group\022\036\n\004cnfg\030\001 \001(\0132"
      "\020.fsm.P0_Group_el\022\036\n\004csvg\030\002 \001(\0132\020.fsm.P0"
      "_Group_el\"2\n\rPO_Subscriber\022\022\n\nsip_number"
      "\030\001 \001(\r\022\r\n\005flags\030\002 \001(\r\"\231\001\n\nPO_Channel\022\025\n\r"
      "self_sip_port\030\001 \001(\r\022\025\n\rself_rtp_port\030\002 \001"
      "(\r\022\027\n\017self_sip_number\030\003 \001(\r\022\016\n\006volume\030\004 "
      "\001(\r\0224\n\021SubscriberForCall\030\005 \003(\0132\022.fsm.PO_"
      "SubscriberB\005\222\?\002\020\014\"~\n\002P0\022\037\n\006client\030\001 \001(\0132"
      "\017.fsm.ClientInfo\022\032\n\003grp\030\002 \001(\0132\r.fsm.P0_G"
      "roup\022\022\n\003mac\030\003 \001(\014B\005\222\?\002\010\006\022\'\n\007channel\030\004 \003("
      "\0132\017.fsm.PO_ChannelB\005\222\?\002\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 593);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fsm_cckconfig_PO.proto", &protobuf_RegisterTypes);
  ::protobuf_nanopb_2eproto::AddDescriptors();
  ::protobuf_fsm_5fcckconfig_5fclientinfo_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_fsm_5fcckconfig_5fPO_2eproto
namespace fsm {

// ===================================================================

void P0_Group_subel::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int P0_Group_subel::kAbonentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

P0_Group_subel::P0_Group_subel()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group_subel.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fsm.P0_Group_subel)
}
P0_Group_subel::P0_Group_subel(const P0_Group_subel& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      abonent_(from.abonent_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:fsm.P0_Group_subel)
}

void P0_Group_subel::SharedCtor() {
}

P0_Group_subel::~P0_Group_subel() {
  // @@protoc_insertion_point(destructor:fsm.P0_Group_subel)
  SharedDtor();
}

void P0_Group_subel::SharedDtor() {
}

void P0_Group_subel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* P0_Group_subel::descriptor() {
  ::protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const P0_Group_subel& P0_Group_subel::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group_subel.base);
  return *internal_default_instance();
}


void P0_Group_subel::Clear() {
// @@protoc_insertion_point(message_clear_start:fsm.P0_Group_subel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  abonent_.Clear();
  _internal_metadata_.Clear();
}

bool P0_Group_subel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fsm.P0_Group_subel)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 abonent = 1 [(.nanopb) = {
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_abonent())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 10u, input, this->mutable_abonent())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fsm.P0_Group_subel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fsm.P0_Group_subel)
  return false;
#undef DO_
}

void P0_Group_subel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fsm.P0_Group_subel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 abonent = 1 [(.nanopb) = {
  if (this->abonent_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _abonent_cached_byte_size_));
  }
  for (int i = 0, n = this->abonent_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->abonent(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fsm.P0_Group_subel)
}

::google::protobuf::uint8* P0_Group_subel::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fsm.P0_Group_subel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 abonent = 1 [(.nanopb) = {
  if (this->abonent_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _abonent_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->abonent_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fsm.P0_Group_subel)
  return target;
}

size_t P0_Group_subel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fsm.P0_Group_subel)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated uint32 abonent = 1 [(.nanopb) = {
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->abonent_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _abonent_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void P0_Group_subel::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fsm.P0_Group_subel)
  GOOGLE_DCHECK_NE(&from, this);
  const P0_Group_subel* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const P0_Group_subel>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fsm.P0_Group_subel)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fsm.P0_Group_subel)
    MergeFrom(*source);
  }
}

void P0_Group_subel::MergeFrom(const P0_Group_subel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fsm.P0_Group_subel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  abonent_.MergeFrom(from.abonent_);
}

void P0_Group_subel::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fsm.P0_Group_subel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void P0_Group_subel::CopyFrom(const P0_Group_subel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fsm.P0_Group_subel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool P0_Group_subel::IsInitialized() const {
  return true;
}

void P0_Group_subel::Swap(P0_Group_subel* other) {
  if (other == this) return;
  InternalSwap(other);
}
void P0_Group_subel::InternalSwap(P0_Group_subel* other) {
  using std::swap;
  abonent_.InternalSwap(&other->abonent_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata P0_Group_subel::GetMetadata() const {
  protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void P0_Group_el::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int P0_Group_el::kGrpFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

P0_Group_el::P0_Group_el()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group_el.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fsm.P0_Group_el)
}
P0_Group_el::P0_Group_el(const P0_Group_el& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      grp_(from.grp_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:fsm.P0_Group_el)
}

void P0_Group_el::SharedCtor() {
}

P0_Group_el::~P0_Group_el() {
  // @@protoc_insertion_point(destructor:fsm.P0_Group_el)
  SharedDtor();
}

void P0_Group_el::SharedDtor() {
}

void P0_Group_el::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* P0_Group_el::descriptor() {
  ::protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const P0_Group_el& P0_Group_el::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group_el.base);
  return *internal_default_instance();
}


void P0_Group_el::Clear() {
// @@protoc_insertion_point(message_clear_start:fsm.P0_Group_el)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  grp_.Clear();
  _internal_metadata_.Clear();
}

bool P0_Group_el::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fsm.P0_Group_el)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .fsm.P0_Group_subel grp = 1 [(.nanopb) = {
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_grp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fsm.P0_Group_el)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fsm.P0_Group_el)
  return false;
#undef DO_
}

void P0_Group_el::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fsm.P0_Group_el)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .fsm.P0_Group_subel grp = 1 [(.nanopb) = {
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->grp_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->grp(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fsm.P0_Group_el)
}

::google::protobuf::uint8* P0_Group_el::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fsm.P0_Group_el)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .fsm.P0_Group_subel grp = 1 [(.nanopb) = {
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->grp_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->grp(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fsm.P0_Group_el)
  return target;
}

size_t P0_Group_el::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fsm.P0_Group_el)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .fsm.P0_Group_subel grp = 1 [(.nanopb) = {
  {
    unsigned int count = static_cast<unsigned int>(this->grp_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->grp(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void P0_Group_el::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fsm.P0_Group_el)
  GOOGLE_DCHECK_NE(&from, this);
  const P0_Group_el* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const P0_Group_el>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fsm.P0_Group_el)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fsm.P0_Group_el)
    MergeFrom(*source);
  }
}

void P0_Group_el::MergeFrom(const P0_Group_el& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fsm.P0_Group_el)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  grp_.MergeFrom(from.grp_);
}

void P0_Group_el::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fsm.P0_Group_el)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void P0_Group_el::CopyFrom(const P0_Group_el& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fsm.P0_Group_el)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool P0_Group_el::IsInitialized() const {
  return true;
}

void P0_Group_el::Swap(P0_Group_el* other) {
  if (other == this) return;
  InternalSwap(other);
}
void P0_Group_el::InternalSwap(P0_Group_el* other) {
  using std::swap;
  CastToBase(&grp_)->InternalSwap(CastToBase(&other->grp_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata P0_Group_el::GetMetadata() const {
  protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void P0_Group::InitAsDefaultInstance() {
  ::fsm::_P0_Group_default_instance_._instance.get_mutable()->cnfg_ = const_cast< ::fsm::P0_Group_el*>(
      ::fsm::P0_Group_el::internal_default_instance());
  ::fsm::_P0_Group_default_instance_._instance.get_mutable()->csvg_ = const_cast< ::fsm::P0_Group_el*>(
      ::fsm::P0_Group_el::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int P0_Group::kCnfgFieldNumber;
const int P0_Group::kCsvgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

P0_Group::P0_Group()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fsm.P0_Group)
}
P0_Group::P0_Group(const P0_Group& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_cnfg()) {
    cnfg_ = new ::fsm::P0_Group_el(*from.cnfg_);
  } else {
    cnfg_ = NULL;
  }
  if (from.has_csvg()) {
    csvg_ = new ::fsm::P0_Group_el(*from.csvg_);
  } else {
    csvg_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:fsm.P0_Group)
}

void P0_Group::SharedCtor() {
  ::memset(&cnfg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&csvg_) -
      reinterpret_cast<char*>(&cnfg_)) + sizeof(csvg_));
}

P0_Group::~P0_Group() {
  // @@protoc_insertion_point(destructor:fsm.P0_Group)
  SharedDtor();
}

void P0_Group::SharedDtor() {
  if (this != internal_default_instance()) delete cnfg_;
  if (this != internal_default_instance()) delete csvg_;
}

void P0_Group::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* P0_Group::descriptor() {
  ::protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const P0_Group& P0_Group::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0_Group.base);
  return *internal_default_instance();
}


void P0_Group::Clear() {
// @@protoc_insertion_point(message_clear_start:fsm.P0_Group)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && cnfg_ != NULL) {
    delete cnfg_;
  }
  cnfg_ = NULL;
  if (GetArenaNoVirtual() == NULL && csvg_ != NULL) {
    delete csvg_;
  }
  csvg_ = NULL;
  _internal_metadata_.Clear();
}

bool P0_Group::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fsm.P0_Group)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .fsm.P0_Group_el cnfg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_cnfg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .fsm.P0_Group_el csvg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_csvg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fsm.P0_Group)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fsm.P0_Group)
  return false;
#undef DO_
}

void P0_Group::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fsm.P0_Group)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fsm.P0_Group_el cnfg = 1;
  if (this->has_cnfg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_cnfg(), output);
  }

  // .fsm.P0_Group_el csvg = 2;
  if (this->has_csvg()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_csvg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fsm.P0_Group)
}

::google::protobuf::uint8* P0_Group::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fsm.P0_Group)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fsm.P0_Group_el cnfg = 1;
  if (this->has_cnfg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_cnfg(), deterministic, target);
  }

  // .fsm.P0_Group_el csvg = 2;
  if (this->has_csvg()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_csvg(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fsm.P0_Group)
  return target;
}

size_t P0_Group::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fsm.P0_Group)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .fsm.P0_Group_el cnfg = 1;
  if (this->has_cnfg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *cnfg_);
  }

  // .fsm.P0_Group_el csvg = 2;
  if (this->has_csvg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *csvg_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void P0_Group::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fsm.P0_Group)
  GOOGLE_DCHECK_NE(&from, this);
  const P0_Group* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const P0_Group>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fsm.P0_Group)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fsm.P0_Group)
    MergeFrom(*source);
  }
}

void P0_Group::MergeFrom(const P0_Group& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fsm.P0_Group)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_cnfg()) {
    mutable_cnfg()->::fsm::P0_Group_el::MergeFrom(from.cnfg());
  }
  if (from.has_csvg()) {
    mutable_csvg()->::fsm::P0_Group_el::MergeFrom(from.csvg());
  }
}

void P0_Group::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fsm.P0_Group)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void P0_Group::CopyFrom(const P0_Group& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fsm.P0_Group)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool P0_Group::IsInitialized() const {
  return true;
}

void P0_Group::Swap(P0_Group* other) {
  if (other == this) return;
  InternalSwap(other);
}
void P0_Group::InternalSwap(P0_Group* other) {
  using std::swap;
  swap(cnfg_, other->cnfg_);
  swap(csvg_, other->csvg_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata P0_Group::GetMetadata() const {
  protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PO_Subscriber::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PO_Subscriber::kSipNumberFieldNumber;
const int PO_Subscriber::kFlagsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PO_Subscriber::PO_Subscriber()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_PO_Subscriber.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fsm.PO_Subscriber)
}
PO_Subscriber::PO_Subscriber(const PO_Subscriber& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&sip_number_, &from.sip_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&flags_) -
    reinterpret_cast<char*>(&sip_number_)) + sizeof(flags_));
  // @@protoc_insertion_point(copy_constructor:fsm.PO_Subscriber)
}

void PO_Subscriber::SharedCtor() {
  ::memset(&sip_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&flags_) -
      reinterpret_cast<char*>(&sip_number_)) + sizeof(flags_));
}

PO_Subscriber::~PO_Subscriber() {
  // @@protoc_insertion_point(destructor:fsm.PO_Subscriber)
  SharedDtor();
}

void PO_Subscriber::SharedDtor() {
}

void PO_Subscriber::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PO_Subscriber::descriptor() {
  ::protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PO_Subscriber& PO_Subscriber::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_PO_Subscriber.base);
  return *internal_default_instance();
}


void PO_Subscriber::Clear() {
// @@protoc_insertion_point(message_clear_start:fsm.PO_Subscriber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&sip_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&flags_) -
      reinterpret_cast<char*>(&sip_number_)) + sizeof(flags_));
  _internal_metadata_.Clear();
}

bool PO_Subscriber::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fsm.PO_Subscriber)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 sip_number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sip_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 flags = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &flags_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fsm.PO_Subscriber)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fsm.PO_Subscriber)
  return false;
#undef DO_
}

void PO_Subscriber::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fsm.PO_Subscriber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 sip_number = 1;
  if (this->sip_number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->sip_number(), output);
  }

  // uint32 flags = 2;
  if (this->flags() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->flags(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fsm.PO_Subscriber)
}

::google::protobuf::uint8* PO_Subscriber::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fsm.PO_Subscriber)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 sip_number = 1;
  if (this->sip_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->sip_number(), target);
  }

  // uint32 flags = 2;
  if (this->flags() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->flags(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fsm.PO_Subscriber)
  return target;
}

size_t PO_Subscriber::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fsm.PO_Subscriber)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 sip_number = 1;
  if (this->sip_number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sip_number());
  }

  // uint32 flags = 2;
  if (this->flags() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->flags());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PO_Subscriber::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fsm.PO_Subscriber)
  GOOGLE_DCHECK_NE(&from, this);
  const PO_Subscriber* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PO_Subscriber>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fsm.PO_Subscriber)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fsm.PO_Subscriber)
    MergeFrom(*source);
  }
}

void PO_Subscriber::MergeFrom(const PO_Subscriber& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fsm.PO_Subscriber)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sip_number() != 0) {
    set_sip_number(from.sip_number());
  }
  if (from.flags() != 0) {
    set_flags(from.flags());
  }
}

void PO_Subscriber::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fsm.PO_Subscriber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PO_Subscriber::CopyFrom(const PO_Subscriber& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fsm.PO_Subscriber)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PO_Subscriber::IsInitialized() const {
  return true;
}

void PO_Subscriber::Swap(PO_Subscriber* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PO_Subscriber::InternalSwap(PO_Subscriber* other) {
  using std::swap;
  swap(sip_number_, other->sip_number_);
  swap(flags_, other->flags_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PO_Subscriber::GetMetadata() const {
  protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PO_Channel::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PO_Channel::kSelfSipPortFieldNumber;
const int PO_Channel::kSelfRtpPortFieldNumber;
const int PO_Channel::kSelfSipNumberFieldNumber;
const int PO_Channel::kVolumeFieldNumber;
const int PO_Channel::kSubscriberForCallFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PO_Channel::PO_Channel()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_PO_Channel.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fsm.PO_Channel)
}
PO_Channel::PO_Channel(const PO_Channel& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      subscriberforcall_(from.subscriberforcall_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&self_sip_port_, &from.self_sip_port_,
    static_cast<size_t>(reinterpret_cast<char*>(&volume_) -
    reinterpret_cast<char*>(&self_sip_port_)) + sizeof(volume_));
  // @@protoc_insertion_point(copy_constructor:fsm.PO_Channel)
}

void PO_Channel::SharedCtor() {
  ::memset(&self_sip_port_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&volume_) -
      reinterpret_cast<char*>(&self_sip_port_)) + sizeof(volume_));
}

PO_Channel::~PO_Channel() {
  // @@protoc_insertion_point(destructor:fsm.PO_Channel)
  SharedDtor();
}

void PO_Channel::SharedDtor() {
}

void PO_Channel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PO_Channel::descriptor() {
  ::protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PO_Channel& PO_Channel::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_PO_Channel.base);
  return *internal_default_instance();
}


void PO_Channel::Clear() {
// @@protoc_insertion_point(message_clear_start:fsm.PO_Channel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  subscriberforcall_.Clear();
  ::memset(&self_sip_port_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&volume_) -
      reinterpret_cast<char*>(&self_sip_port_)) + sizeof(volume_));
  _internal_metadata_.Clear();
}

bool PO_Channel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fsm.PO_Channel)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 self_sip_port = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &self_sip_port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 self_rtp_port = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &self_rtp_port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 self_sip_number = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &self_sip_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 volume = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &volume_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .fsm.PO_Subscriber SubscriberForCall = 5 [(.nanopb) = {
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_subscriberforcall()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fsm.PO_Channel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fsm.PO_Channel)
  return false;
#undef DO_
}

void PO_Channel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fsm.PO_Channel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 self_sip_port = 1;
  if (this->self_sip_port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->self_sip_port(), output);
  }

  // uint32 self_rtp_port = 2;
  if (this->self_rtp_port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->self_rtp_port(), output);
  }

  // uint32 self_sip_number = 3;
  if (this->self_sip_number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->self_sip_number(), output);
  }

  // uint32 volume = 4;
  if (this->volume() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->volume(), output);
  }

  // repeated .fsm.PO_Subscriber SubscriberForCall = 5 [(.nanopb) = {
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->subscriberforcall_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->subscriberforcall(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fsm.PO_Channel)
}

::google::protobuf::uint8* PO_Channel::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fsm.PO_Channel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 self_sip_port = 1;
  if (this->self_sip_port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->self_sip_port(), target);
  }

  // uint32 self_rtp_port = 2;
  if (this->self_rtp_port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->self_rtp_port(), target);
  }

  // uint32 self_sip_number = 3;
  if (this->self_sip_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->self_sip_number(), target);
  }

  // uint32 volume = 4;
  if (this->volume() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->volume(), target);
  }

  // repeated .fsm.PO_Subscriber SubscriberForCall = 5 [(.nanopb) = {
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->subscriberforcall_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->subscriberforcall(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fsm.PO_Channel)
  return target;
}

size_t PO_Channel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fsm.PO_Channel)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .fsm.PO_Subscriber SubscriberForCall = 5 [(.nanopb) = {
  {
    unsigned int count = static_cast<unsigned int>(this->subscriberforcall_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->subscriberforcall(static_cast<int>(i)));
    }
  }

  // uint32 self_sip_port = 1;
  if (this->self_sip_port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->self_sip_port());
  }

  // uint32 self_rtp_port = 2;
  if (this->self_rtp_port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->self_rtp_port());
  }

  // uint32 self_sip_number = 3;
  if (this->self_sip_number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->self_sip_number());
  }

  // uint32 volume = 4;
  if (this->volume() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->volume());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PO_Channel::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fsm.PO_Channel)
  GOOGLE_DCHECK_NE(&from, this);
  const PO_Channel* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PO_Channel>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fsm.PO_Channel)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fsm.PO_Channel)
    MergeFrom(*source);
  }
}

void PO_Channel::MergeFrom(const PO_Channel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fsm.PO_Channel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  subscriberforcall_.MergeFrom(from.subscriberforcall_);
  if (from.self_sip_port() != 0) {
    set_self_sip_port(from.self_sip_port());
  }
  if (from.self_rtp_port() != 0) {
    set_self_rtp_port(from.self_rtp_port());
  }
  if (from.self_sip_number() != 0) {
    set_self_sip_number(from.self_sip_number());
  }
  if (from.volume() != 0) {
    set_volume(from.volume());
  }
}

void PO_Channel::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fsm.PO_Channel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PO_Channel::CopyFrom(const PO_Channel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fsm.PO_Channel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PO_Channel::IsInitialized() const {
  return true;
}

void PO_Channel::Swap(PO_Channel* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PO_Channel::InternalSwap(PO_Channel* other) {
  using std::swap;
  CastToBase(&subscriberforcall_)->InternalSwap(CastToBase(&other->subscriberforcall_));
  swap(self_sip_port_, other->self_sip_port_);
  swap(self_rtp_port_, other->self_rtp_port_);
  swap(self_sip_number_, other->self_sip_number_);
  swap(volume_, other->volume_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PO_Channel::GetMetadata() const {
  protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void P0::InitAsDefaultInstance() {
  ::fsm::_P0_default_instance_._instance.get_mutable()->client_ = const_cast< ::fsm::ClientInfo*>(
      ::fsm::ClientInfo::internal_default_instance());
  ::fsm::_P0_default_instance_._instance.get_mutable()->grp_ = const_cast< ::fsm::P0_Group*>(
      ::fsm::P0_Group::internal_default_instance());
}
void P0::clear_client() {
  if (GetArenaNoVirtual() == NULL && client_ != NULL) {
    delete client_;
  }
  client_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int P0::kClientFieldNumber;
const int P0::kGrpFieldNumber;
const int P0::kMacFieldNumber;
const int P0::kChannelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

P0::P0()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:fsm.P0)
}
P0::P0(const P0& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      channel_(from.channel_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  mac_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.mac().size() > 0) {
    mac_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mac_);
  }
  if (from.has_client()) {
    client_ = new ::fsm::ClientInfo(*from.client_);
  } else {
    client_ = NULL;
  }
  if (from.has_grp()) {
    grp_ = new ::fsm::P0_Group(*from.grp_);
  } else {
    grp_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:fsm.P0)
}

void P0::SharedCtor() {
  mac_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&client_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&grp_) -
      reinterpret_cast<char*>(&client_)) + sizeof(grp_));
}

P0::~P0() {
  // @@protoc_insertion_point(destructor:fsm.P0)
  SharedDtor();
}

void P0::SharedDtor() {
  mac_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete client_;
  if (this != internal_default_instance()) delete grp_;
}

void P0::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* P0::descriptor() {
  ::protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const P0& P0::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_fsm_5fcckconfig_5fPO_2eproto::scc_info_P0.base);
  return *internal_default_instance();
}


void P0::Clear() {
// @@protoc_insertion_point(message_clear_start:fsm.P0)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  channel_.Clear();
  mac_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && client_ != NULL) {
    delete client_;
  }
  client_ = NULL;
  if (GetArenaNoVirtual() == NULL && grp_ != NULL) {
    delete grp_;
  }
  grp_ = NULL;
  _internal_metadata_.Clear();
}

bool P0::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:fsm.P0)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .fsm.ClientInfo client = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_client()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .fsm.P0_Group grp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_grp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes mac = 3 [(.nanopb) = {
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_mac()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .fsm.PO_Channel channel = 4 [(.nanopb) = {
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_channel()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:fsm.P0)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:fsm.P0)
  return false;
#undef DO_
}

void P0::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:fsm.P0)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fsm.ClientInfo client = 1;
  if (this->has_client()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_client(), output);
  }

  // .fsm.P0_Group grp = 2;
  if (this->has_grp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_grp(), output);
  }

  // bytes mac = 3 [(.nanopb) = {
  if (this->mac().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->mac(), output);
  }

  // repeated .fsm.PO_Channel channel = 4 [(.nanopb) = {
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->channel_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->channel(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:fsm.P0)
}

::google::protobuf::uint8* P0::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:fsm.P0)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .fsm.ClientInfo client = 1;
  if (this->has_client()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_client(), deterministic, target);
  }

  // .fsm.P0_Group grp = 2;
  if (this->has_grp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_grp(), deterministic, target);
  }

  // bytes mac = 3 [(.nanopb) = {
  if (this->mac().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->mac(), target);
  }

  // repeated .fsm.PO_Channel channel = 4 [(.nanopb) = {
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->channel_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->channel(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fsm.P0)
  return target;
}

size_t P0::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fsm.P0)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .fsm.PO_Channel channel = 4 [(.nanopb) = {
  {
    unsigned int count = static_cast<unsigned int>(this->channel_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->channel(static_cast<int>(i)));
    }
  }

  // bytes mac = 3 [(.nanopb) = {
  if (this->mac().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->mac());
  }

  // .fsm.ClientInfo client = 1;
  if (this->has_client()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *client_);
  }

  // .fsm.P0_Group grp = 2;
  if (this->has_grp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *grp_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void P0::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:fsm.P0)
  GOOGLE_DCHECK_NE(&from, this);
  const P0* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const P0>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:fsm.P0)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:fsm.P0)
    MergeFrom(*source);
  }
}

void P0::MergeFrom(const P0& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:fsm.P0)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  channel_.MergeFrom(from.channel_);
  if (from.mac().size() > 0) {

    mac_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mac_);
  }
  if (from.has_client()) {
    mutable_client()->::fsm::ClientInfo::MergeFrom(from.client());
  }
  if (from.has_grp()) {
    mutable_grp()->::fsm::P0_Group::MergeFrom(from.grp());
  }
}

void P0::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:fsm.P0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void P0::CopyFrom(const P0& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fsm.P0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool P0::IsInitialized() const {
  return true;
}

void P0::Swap(P0* other) {
  if (other == this) return;
  InternalSwap(other);
}
void P0::InternalSwap(P0* other) {
  using std::swap;
  CastToBase(&channel_)->InternalSwap(CastToBase(&other->channel_));
  mac_.Swap(&other->mac_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(client_, other->client_);
  swap(grp_, other->grp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata P0::GetMetadata() const {
  protobuf_fsm_5fcckconfig_5fPO_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_fsm_5fcckconfig_5fPO_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace fsm
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fsm::P0_Group_subel* Arena::CreateMaybeMessage< ::fsm::P0_Group_subel >(Arena* arena) {
  return Arena::CreateInternal< ::fsm::P0_Group_subel >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fsm::P0_Group_el* Arena::CreateMaybeMessage< ::fsm::P0_Group_el >(Arena* arena) {
  return Arena::CreateInternal< ::fsm::P0_Group_el >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fsm::P0_Group* Arena::CreateMaybeMessage< ::fsm::P0_Group >(Arena* arena) {
  return Arena::CreateInternal< ::fsm::P0_Group >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fsm::PO_Subscriber* Arena::CreateMaybeMessage< ::fsm::PO_Subscriber >(Arena* arena) {
  return Arena::CreateInternal< ::fsm::PO_Subscriber >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fsm::PO_Channel* Arena::CreateMaybeMessage< ::fsm::PO_Channel >(Arena* arena) {
  return Arena::CreateInternal< ::fsm::PO_Channel >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::fsm::P0* Arena::CreateMaybeMessage< ::fsm::P0 >(Arena* arena) {
  return Arena::CreateInternal< ::fsm::P0 >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
